app/models.py
class Source:
    '''
    Source class to define News Objects
    '''

    def __init__(self,id,name,description,url,category,language,country):
        self.id =id
        self.name=name
        self.description=description
        self.url=url
        self.category=category
        self.language=language
        self.country=country

class Article:
    '''
    Article class to define News objects
    '''
    def __init__(self,author,title,description,url,urlToImage,publishedAt,content):
        self.author = author
        self.title = title
        self.description = description
        self.url = url
        self.urlToImage = urlToImage
        self.publishedAt = publishedAt
        self.content = content


        
        

app/models/source.py
class Source:
    '''
    Source class to define News Objects
    '''

    def __init__(self,id,name,description,url,category,language,country):
        self.id =id
        self.name=name
        self.description=description
        self.url=url
        self.category=category
        self.language=language
        self.country=country

class Article:
    '''
    Article class to define News objects
    '''
    def __init__(self,author,title,description,url,urlToImage,publishedAt,content):
        self.author = author
        self.title = title
        self.description = description
        self.url = url
        self.urlToImage = urlToImage
        self.publishedAt = publishedAt
        self.content = content


        
        

app/__init__.py
from flask import Flask
from .config import DevConfig
from flask_bootstrap import Bootstrap

# Initializing application
app = Flask(__name__,instance_relative_config = True)

# Setting up configuration
app.config.from_object(DevConfig)
app.config.from_pyfile('config.py')

#Initializing Flask Extensions
bootstrap = Bootstrap(app)

from app import views
from app import error

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,error

def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/views.py
from flask import render_template,request,redirect,url_for
from . import main
from ..request import get_news_sources,get_articles

# Views
@main.route('/')
def index():

    '''
    View root page function that returns the index page and its data
    '''

    # Retrieve sources from news api
    sources= get_news_sources()

    return render_template('index.html',sources=sources)

@main.route('/articles/<string:source_id>')
def articles(source_id):
    '''
    View Newse page function that returns the News details page and its data
    '''

    # Retrieve articles for source_id
    articles = get_articles(source_id)

    return render_template('articles.html', articles = articles)

app/templates/articles.html
 {% extends 'base.html'%} {% block content %}

<div class="card-deck">
    {% for article in articles %}
    <div class="card">
        <img class="card-img-top" src="{{ article['urlToImage'] }}" alt="Card image cap" height="286px" width="286px">
        <div class="card-body">
            <h5 class="card-title"><a href="{{ article['url'] }}" target="_blank">{{ article['title'] }}</a> </h5>
            <p class="card-text">{{ article['description'] }}</p>
        </div>
    </div>
    {% endfor %}
</div>

<!--table class="table">
    <thead>
        <tr>
            <th>
                <h2>Image</h2>
            </th>
            <th>
                <h2>Description</h2>
            </th>
            <th>
                <h2>Published Date</h2>
            </th>
        </tr>
    </thead>
    <tbody>
        {% for article in articles %}
        <tr>
            <td><img src="{{ article['urlToImage'] }}" alt="no image" height=200px width=250px></td>
            <td>
                <a href="{{ article['url'] }}" target="_blank"> {{ article['description'] }} </a>
            </td>
            <td>{{ article['publishedAt'] }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table-->
{% endblock %}

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Navbar block  -->
{% block navbar %} {% include 'navbar.html' %} {% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html'%} {% block content %}
<h1>WHOOOPS we can't find that page</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%} {% block content %}
<table class="table" align="center">
    <thead>
        <tr>
            <th>
                <h1>News Sources</h1>
            </th>

        </tr>
    </thead>
    <tbody>
        {% for source in sources%}
        <tr>
            <td>
                <a href="{{ url_for('main.articles', source_id=source['id']) }}">
                    <h2>{{source.name}}</h2>
                </a>
            </td>

        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">News App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
        </ul>
    </div>
</nav>